### ISSUE TITLE
Ability to pull credentials from `get: ` & use it in later steps of pipeline

### ISSUE THREAD

**Issue by aegershman** [cloudfoundry-community/credhub-resource#3]
If I perform a `get: credhub`, I'm only able to determine if a credhub path has changed.  I'd like to be able to use the output of `credhub get -n /my/path` in later steps of the pipeline.

I'm imagining something that could be used alongside the [terraform resource](https://github.com/ljfranklin/terraform-resource) or the [bosh deployment resource](https://github.com/concourse/bosh-deployment-resource)

This isn't 
```yaml
- get: credhub
- put: terraform
   params:
      var_files: credhub/output.yml
- put: some-bosh-deployment
   params:
      var_files: credhub/output.yml
```
